name: generate animation

on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"

  # Allows manual triggering from GitHub UI
  workflow_dispatch:

  # Run on every push to master or main
  push:
    branches:
      - master
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Generate custom SVGs
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-light.svg?color_snake=#FF5733&color_dots=#f0f8ff,#87cefa,#4682b4,#1e90ff,#00008b
            dist/snake-dark.svg?palette=github-dark&color_snake=#00ffcc&color_dots=#111111,#333333,#555555,#777777,#ffffff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Debug - list generated files
      - name: List generated SVG files
        run: ls -la dist

      # Step 3: Push to the output branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
